name: develop-ci

on:
  push:
    branches:
      - "develop"

jobs:

  integration:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore
    - name: Build
      working-directory: ./src
      run: dotnet build --nologo --no-restore --configuration Release
    - name: Test
      working-directory: ./src
      run: dotnet test --nologo --no-build --no-restore --configuration Release